version: '3.8'

services:
  attacker:
    build: { context: .. }
    hostname: kali-attacker
    networks: [autopt-net]
    dns: [ "8.8.8.8", "8.8.4.4" ]
  
  victim:
    image: vulhub/teamcity:2023.05.3
    ports: ["8111:8111"]
    networks:
      autopt-net:
        ipv4_address: 172.20.0.3
    dns: [ "8.8.8.8", "8.8.4.4" ]

networks:
  autopt-net:
    driver: bridge
    ipam: { config: [{ subnet: "172.20.0.0/16" }] }